# backend/app/services/billing_service.py
"""
Clinical billing assembly service.

Combines ICD-10-CM diagnosis codes and ICD-10-PCS procedure codes into a
single, insurer-agnostic BillingClaim per encounter.  The claim is stored as
JSON in the DB and can be exported to any insurer (PM-JAY, CGHS, ABHA, private).
"""

from __future__ import annotations

import logging
from datetime import date
from typing import Any, Optional

from pydantic import BaseModel

from app.services.icd_coding_service import ICDSuggestion
from app.services.procedure_coding_service import ProcedureSuggestion

logger = logging.getLogger(__name__)


class BillingClaim(BaseModel):
    patient_id: int
    encounter_date: str  # ISO date: "2026-03-02"
    principal_diagnosis_code: str  # Highest-confidence ICD-10-CM code
    principal_diagnosis_description: str
    diagnosis_codes: list[dict[str, Any]]  # Full ICDSuggestion list as dicts
    procedure_codes: list[dict[str, Any]]  # Full ProcedureSuggestion list as dicts
    billing_notes: str  # Human-readable summary for insurer forms
    coding_status: str  # "auto_coded" | "confirmed" | "partial"


class BillingService:
    """Stateless — instantiate freely."""

    def assemble(
        self,
        patient_id: int,
        patient_name: Optional[str],
        diagnosis_codes: list[ICDSuggestion],
        procedure_codes: list[ProcedureSuggestion],
        chief_complaint: Optional[str] = None,
        symptoms: Optional[list[str]] = None,
        medications: Optional[list[str]] = None,
        procedures_performed: Optional[list[str]] = None,
    ) -> BillingClaim:
        """
        Assemble a complete BillingClaim from both code sets.
        """
        today = date.today().isoformat()

        # Principal diagnosis = highest-confidence ICD-10-CM code
        principal_dx = diagnosis_codes[0] if diagnosis_codes else None
        principal_code = principal_dx.code if principal_dx else "Z00.00"
        principal_desc = principal_dx.description if principal_dx else "General medical examination"

        billing_notes = self._build_billing_notes(
            patient_name=patient_name,
            chief_complaint=chief_complaint,
            symptoms=symptoms,
            diagnosis_codes=diagnosis_codes,
            procedure_codes=procedure_codes,
            medications=medications,
            procedures_performed=procedures_performed,
        )

        status = "auto_coded"
        if not diagnosis_codes and not procedure_codes:
            status = "partial"

        return BillingClaim(
            patient_id=patient_id,
            encounter_date=today,
            principal_diagnosis_code=principal_code,
            principal_diagnosis_description=principal_desc,
            diagnosis_codes=[s.model_dump() for s in diagnosis_codes],
            procedure_codes=[s.model_dump() for s in procedure_codes],
            billing_notes=billing_notes,
            coding_status=status,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_billing_notes(
        patient_name: Optional[str],
        chief_complaint: Optional[str],
        symptoms: Optional[list[str]],
        diagnosis_codes: list[ICDSuggestion],
        procedure_codes: list[ProcedureSuggestion],
        medications: Optional[list[str]],
        procedures_performed: Optional[list[str]],
    ) -> str:
        """Produce a structured plain-text billing narrative."""
        lines: list[str] = []

        if patient_name:
            lines.append(f"Patient: {patient_name}")

        if chief_complaint:
            lines.append(f"Presenting Complaint: {chief_complaint}")

        if symptoms:
            lines.append(f"Symptoms: {', '.join(symptoms)}")

        if diagnosis_codes:
            dx_parts = [f"{s.code} ({s.description})" for s in diagnosis_codes]
            lines.append(f"ICD-10-CM Diagnosis Codes: {'; '.join(dx_parts)}")

        if procedures_performed:
            lines.append(f"Procedures Performed: {', '.join(procedures_performed)}")

        if procedure_codes:
            px_parts = [f"{s.code} ({s.description})" for s in procedure_codes]
            lines.append(f"ICD-10-PCS Procedure Codes: {'; '.join(px_parts)}")

        if medications:
            lines.append(f"Medications Prescribed: {', '.join(medications)}")

        lines.append(
            "Note: Codes auto-generated by RuralMedAI offline NLP engine. "
            "Subject to clinician review before insurance submission."
        )

        return "\n".join(lines)
