
import type { Vitals } from '@/types';

// Loose structural type for documents printed from encounter/EHR records. Kept
// optional so the same templates render from either a live form or a DB row.
export interface TemplatePatient {
    id?: number;
    name?: string;
    age?: string;
    gender?: string;
    contact?: string;
    created_at?: string;
    pmjay_id?: string;
    cghs_id?: string;
    rank?: string;
    service_no?: string;
    chief_complaint?: string;
    symptoms?: string[];
    vitals?: Vitals;
    medical_history?: string[];
    medications?: string[];
    tentative_doctor_diagnosis?: string;
    initial_llm_diagnosis?: string;
}

export const getAyushmanTemplate = (patient: TemplatePatient) => {
    return `
    <html>
    <head>
        <title>Discharge Summary - Ayushman Bharat PM-JAY</title>
        <style>
            body { font-family: 'Times New Roman', serif; padding: 40px; }
            .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 20px; }
            .logo-text { font-size: 24px; font-weight: bold; text-transform: uppercase; }
            .sub-header { font-size: 14px; margin-top: 5px; }
            .section-title { font-size: 16px; font-weight: bold; background: #eee; padding: 5px; margin-top: 20px; border: 1px solid #000; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            td, th { border: 1px solid #000; padding: 8px; font-size: 14px; text-align: left; }
            .footer { margin-top: 50px; text-align: center; font-size: 12px; border-top: 1px solid #ccc; padding-top: 10px; color: #555; }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="logo-text">Pradhan Mantri Jan Arogya Yojana (PM-JAY)</div>
            <div class="sub-header">National Health Authority, Government of India</div>
            <h2>DISCHARGE SUMMARY</h2>
        </div>

        <table>
            <tr>
                <td><strong>Patient Name:</strong> ${patient.name || "N/A"}</td>
                <td><strong>PMJAY ID:</strong> ${patient.pmjay_id || "N/A"}</td>
            </tr>
            <tr>
                <td><strong>Age/Gender:</strong> ${patient.age || "--"} / ${patient.gender || "--"}</td>
                <td><strong>Contact:</strong> ${patient.contact || "N/A"}</td>
            </tr>
            <tr>
                <td><strong>Admission Date:</strong> ${patient.created_at ? new Date(patient.created_at).toLocaleDateString() : "N/A"}</td>
                <td><strong>Discharge Date:</strong> ${new Date().toLocaleDateString()}</td>
            </tr>
            <tr>
                <td colspan="2"><strong>Hospital Name:</strong> RuralMed Community Health Centre</td>
            </tr>
        </table>

        <div class="section-title">CLINICAL SUMMARY</div>
        <p><strong>Chief Complaint:</strong> ${patient.chief_complaint || "Not recorded"}</p>
        <p><strong>History of Present Illness:</strong> ${patient.medical_history?.join(", ") || "None"}</p>

        <div class="section-title">VITALS AT ADMISSION</div>
        <table>
            <tr>
                <td><strong>BP:</strong> ${patient.vitals?.blood_pressure || "--"}</td>
                <td><strong>Pulse:</strong> ${patient.vitals?.pulse || "--"} /min</td>
                <td><strong>Temp:</strong> ${patient.vitals?.temperature || "--"}</td>
                <td><strong>SpO2:</strong> ${patient.vitals?.spo2 || "--"}%</td>
            </tr>
        </table>

        <div class="section-title">DIAGNOSIS</div>
        <p><strong>Provisional Diagnosis:</strong> ${patient.tentative_doctor_diagnosis || "Under Evaluation"}</p>
        <p><strong>Final Diagnosis:</strong> ${patient.initial_llm_diagnosis || "Pending Confirmation"}</p>

        <div class="section-title">TREATMENT GIVEN</div>
        <ul>
            ${patient.medications && patient.medications.length > 0 ? patient.medications.map((m: string) => `<li>${m}</li>`).join('') : "<li>No specific medications recorded</li>"}
        </ul>

        <div class="section-title">ADVICE ON DISCHARGE</div>
        <p>1. Review in OPD after 7 days.</p>
        <p>2. Continue prescribed medications.</p>
        <p>3. Emergency contact: 108 / 104.</p>

        <div style="margin-top: 60px; display: flex; justify-content: space-between;">
            <div style="text-align: center;">
                _________________________<br>
                Signature of Patient
            </div>
            <div style="text-align: center;">
                _________________________<br>
                <strong>Dr. [Name]</strong><br>
                Medical Officer<br>
                (Signature & Seal)
            </div>
        </div>

        <div class="footer">
            Generated by RuralMedAI - AI for Rural Healthcare
        </div>
    </body>
    </html>
    `;
};

export const getCGHSTemplate = (patient: TemplatePatient) => {
    return `
    <html>
    <head>
        <title>CGHS Prescription Slip</title>
        <style>
            body { font-family: 'Times New Roman', serif; padding: 40px; }
            .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 15px; margin-bottom: 20px; }
            .logo-text { font-size: 22px; font-weight: bold; }
            .sub-header { font-size: 14px; }
            .meta-table { width: 100%; border: none; margin-bottom: 20px; }
            .meta-table td { border: none; padding: 5px; font-size: 14px; }
            .rx-section { margin-top: 20px; min-height: 300px; border: 1px solid #000; padding: 20px; }
            .rx-symbol { font-size: 40px; font-weight: bold; font-style: italic; margin-bottom: 10px; }
            .med-list { list-style-type: decimal; padding-left: 20px; }
            .med-list li { margin-bottom: 10px; font-size: 16px; }
            .footer { margin-top: 50px; text-align: center; font-size: 12px; border-top: 1px solid #ccc; padding-top: 10px; color: #555; }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="logo-text">Central Government Health Scheme (CGHS)</div>
            <div class="sub-header">Ministry of Health & Family Welfare, Govt. of India</div>
            <h3>PRESCRIPTION SLIP</h3>
        </div>

        <table class="meta-table">
            <tr>
                <td><strong>Beneficiary Name:</strong> ${patient.name}</td>
                <td><strong>Ben ID:</strong> ${patient.cghs_id || "___________"}</td>
            </tr>
            <tr>
                <td><strong>Age/Sex:</strong> ${patient.age}/${patient.gender}</td>
                <td><strong>Date:</strong> ${patient.created_at ? new Date(patient.created_at).toLocaleDateString() : new Date().toLocaleDateString()}</td>
            </tr>
            <tr>
                <td><strong>CGHS Wellness Centre:</strong> RuralMed CHC</td>
                <td><strong>Token No:</strong> ${patient.id}</td>
            </tr>
        </table>

        <hr style="border-top: 1px dashed #000;">

        <div style="padding: 10px 0;">
            <strong>Diagnosis:</strong> ${patient.tentative_doctor_diagnosis || "Under Evaluation"}
        </div>
        
        <div style="padding: 10px 0;">
             <strong>Vitals:</strong> BP: ${patient.vitals?.blood_pressure || "--"} | Pulse: ${patient.vitals?.pulse || "--"} | Temp: ${patient.vitals?.temperature || "--"}
        </div>

        <div class="rx-section">
            <div class="rx-symbol">Rx</div>
            <ul class="med-list">
                ${patient.medications && patient.medications.length > 0 ? patient.medications.map((m: string) => `<li>${m}</li>`).join('') : "<li>As per Specialist advice</li>"}
            </ul>
        </div>

        <div style="margin-top: 30px;">
            <strong>Advice / Instructions:</strong><br>
            ${patient.symptoms && patient.symptoms.length > 0 ? "For symptoms: " + patient.symptoms.join(", ") : "Review after 2 weeks."}
        </div>

        <div style="margin-top: 60px; text-align: right;">
            _________________________<br>
            <strong>Medical Officer / Specialist</strong><br>
            Reg. No: ____________<br>
            (Sign & Stamp)
        </div>

        <div class="footer">
            Generated by RuralMedAI - AI for Rural Healthcare
        </div>
    </body>
    </html>
    `;
};

export const getECHSTemplate = (patient: TemplatePatient) => {
    return `
    <html>
    <head>
        <title>ECHS Medical Slip</title>
        <style>
            body { font-family: 'Times New Roman', serif; padding: 40px; }
            .header { text-align: center; border: 2px solid #000; padding: 15px; margin-bottom: 20px; }
            .logo-text { font-size: 24px; font-weight: bold; }
            .sub-header { font-size: 14px; font-weight: bold; margin-top: 5px; }
            .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 20px; border: 1px solid #000; padding: 10px; }
            .info-item { font-size: 14px; }
            .clinical-box { border: 1px solid #000; padding: 15px; min-height: 400px; }
            .rx-header { font-size: 18px; font-weight: bold; text-decoration: underline; margin-bottom: 10px; }
            .footer { margin-top: 50px; text-align: center; font-size: 12px; border-top: 1px solid #ccc; padding-top: 10px; color: #555; }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="logo-text">ECHS POLYCLINIC</div>
            <div class="sub-header">EX-SERVICEMEN CONTRIBUTORY HEALTH SCHEME</div>
            <div>Department of Ex-Servicemen Welfare, Ministry of Defence</div>
        </div>

        <div class="info-grid">
            <div class="info-item"><strong>Service No:</strong> ${patient.service_no || "___________"}</div>
            <div class="info-item"><strong>Rank:</strong> ${patient.rank || "___________"}</div>
            <div class="info-item"><strong>Name:</strong> ${patient.name}</div>
            <div class="info-item"><strong>Age/Gender:</strong> ${patient.age} / ${patient.gender}</div>
            <div class="info-item"><strong>Unit/Depot:</strong> ___________</div>
            <div class="info-item"><strong>Date:</strong> ${patient.created_at ? new Date(patient.created_at).toLocaleDateString() : new Date().toLocaleDateString()}</div>
        </div>

        <div class="clinical-box">
            <p><strong>Chief Complaints:</strong> ${patient.chief_complaint || "--"}</p>
            <p><strong>Diagnosis:</strong> ${patient.tentative_doctor_diagnosis || "--"}</p>
            
            <hr>
            
            <div class="rx-header">TREATMENT / MEDICINES</div>
            <ol style="margin-top: 10px; font-size: 16px; line-height: 1.6;">
                ${patient.medications && patient.medications.length > 0 ? patient.medications.map((m: string) => `<li>${m}</li>`).join('') : "<li>No medications prescribed</li>"}
            </ol>

            <div style="margin-top: 40px;">
                <strong>Disposal / Referral:</strong><br>
                Review SOS.
            </div>
        </div>

        <div style="margin-top: 60px; display: flex; justify-content: space-between;">
            <div>
                Verified By:<br>
                <strong>OIC Polyclinic</strong>
            </div>
            <div style="text-align: right;">
                _________________________<br>
                <strong>Medical Officer</strong><br>
                (Signature with Stamp)
            </div>
        </div>

        <div class="footer">
            Generated by RuralMedAI - AI for Rural Healthcare
        </div>
    </body>
    </html>
    `;
};
